name: xai-chest-xray
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - jupyter>=1.0.0
  - ipykernel>=6.25.0
  - notebook>=7.0.0
  - tqdm>=4.65.0
  - pyyaml>=6.0
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - black>=23.7.0
  - flake8>=6.0.0
  - pip:
    - torch>=2.0.0
    - torchvision>=0.15.0
    - torchaudio>=2.0.0
    - opencv-python>=4.8.0
    - Pillow>=10.0.0
    - albumentations>=1.3.0
    - imgaug>=0.4.0
    - scikit-image>=0.21.0
    - shap>=0.42.0
    - lime>=0.2.0.1
    - captum>=0.6.0
    - grad-cam>=1.4.0
    - plotly>=5.15.0
    - bokeh>=3.2.0
    - streamlit>=1.28.0
    - dash>=2.14.0
    - flask>=2.3.0
    - h5py>=3.9.0
    - pydicom>=2.4.0
    - nibabel>=5.1.0
    - joblib>=1.3.0
    - configparser>=5.3.0
    - python-dotenv>=1.0.0
    - loguru>=0.7.0
    - pytest-mock>=3.11.0
    - isort>=5.12.0
    - mypy>=1.5.0
    - requests>=2.31.0
    - urllib3>=2.0.0
    - pathlib2>=2.3.7
    - SimpleITK>=2.2.0
    - medpy>=0.4.0
    - psutil>=5.9.0
    - GPUtil>=1.4.0
    - sphinx>=7.1.0
    - sphinx-rtd-theme>=1.3.0 